Update djtest
datajoint/djtest-docker pull request #5
Opened 2022-04-07 19:38 UTC by A-Baji

2022-04-11 23:13 UTC, A-Baji commented
Supersedes #4

2022-04-12 15:46 UTC, guzman-raphael requested changes
@A-Baji Exciting stuff! :star_struck: We are getting so close to having things ready for updating our test images. :+1: 

Suggesting only minor corrections.

2022-04-12 15:46 UTC, guzman-raphael commented on dist/alpine/Dockerfile
> +	maintainerCompany="DataJoint"
You can update this to be more generic than calling me out specifically. :sweat_smile: 

Perhaps:

```suggestion
LABEL maintainerName="DataJoint Contributors" \
	maintainerEmail="service-health@datajoint.com" \
	maintainerCompany="DataJoint"
```

2022-04-12 15:46 UTC, guzman-raphael commented on dist/alpine/Dockerfile
> +EXPOSE 8888
We can remove this. We use this port for serving Jupyter. Not applicable here.

2022-04-12 16:22 UTC, guzman-raphael approved these changes

2022-04-12 16:22 UTC, merged